#!/bin/sh

. "$(dirname "$0")/_common.sh"

account='training-staging'

if [ "$1" = "" ]
then
  repo="caption-this"
else
  repo=$1
fi

# Build the site
#
# Generate the Jekyll site with an alterate baseurl for the intenral-only
# staging site, but don't start a local server.
status "Building site..."
DISABLE_WHITELIST=1 bundle exec jekyll build --baseurl "/${account}/${repo}"

# Create a temp Git repo to push from
#
# 1. From the compiled Jekyll `_site` directory
# 2. Initialize a new repo within that directory
# 3. Add a new remote called staging that we can push to
# 4. Add all our files
# 5. Write a generic commit message
status "Creating a temp Git repo..."
cd _site && git init && git remote add staging https://ghe.io/${account}/${repo}.git && git add . && git commit -m "Staging latest changes"

# Push the site
#
# Push the new `_site` temporary repo to our remote staging repo, then remove
# the remote again to do it all over again afterwards.
status "Publishing..."
git push staging master:gh-pages --force && git remote rm staging

# Celebrate and open the staging site
printf "\n${GREEN}# Success!${RESET}\n"
open https://pages.ghe.io/${account}/${repo}/
